service:
  name: ThisIsBac APIs Documentation
  description: API specification for ThisIsBac blog || baseUrl="/api/v1"
  apiVersion: 0.1.0
  docsBaseUrl: /docs/api
  baseUrl: /api/v1

server:
  keepAlive: 80000
  cors:
    allowedHeaders: 'authorization,content-type'
    exposedHeaders: 'authorization,x-response-time,x-request-id, x-pagination-page, x-pagination-page-size, x-pagination-total'

accuracy:
  prefixUrl: https://www.thisisbac.com

jimp:
  x-logo-opt-1: 5
  y-logo-opt-1: 5
  x-text-opt-1: 50
  y-text-opt-1: 50